In [10]:
import pandas as pd

# Indexes - How to Set, Reset, and Use Indexes

In [11]:
# make dataset
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@email.com", "JohnDoe@email.com"],
}

# construct dataframe from dataset
df = pd.DataFrame(people)

# display dataframe
df.head()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [12]:
df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [13]:
# Set the DataFrame index (row labels) using one or more existing columns
df.set_index("email")

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [14]:
# consider email address as the unique identifier of each row
df.set_index("email", inplace=True)

In [15]:
df.head()

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [16]:
# Access a group of rows and columns by label
df.loc["CoreyMSchafer@gmail.com"]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: object

In [17]:
# locate a row
df.loc["CoreyMSchafer@gmail.com", "last"]

'Schafer'

In [18]:
df.iloc[0]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: object

In [20]:
# Reset the index of the DataFrame, and use the default one instead
df.reset_index(inplace=True)

df

   index                    email  first     last
0      0  CoreyMSchafer@gmail.com  Corey  Schafer
1      1        JaneDoe@email.com   Jane      Doe
2      2        JohnDoe@email.com   John      Doe

# Indexing on Stack-Overflow Dataset

In [19]:
# load datasets 
df = pd.read_csv("data/survey_results_public.csv", index_col="Respondent")
schema_df = pd.read_csv("data/survey_results_schema.csv", index_col="Column")

# set viewing option of pandas to show all column
pd.set_option("display.max_columns", 85)
pd.set_option("display.max_rows", 85)

In [20]:
df.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [21]:
df.loc[10, "MgrIdiot"]

'Somewhat confident'

In [40]:
# make search by label easy by using changing index column
schema_df.loc["MgrIdiot", "QuestionText"]

'How confident are you that your manager knows what they’re doing?'

In [23]:
## sort based on column label/index 
# It will be alphabetical here because labels are strings
schema_df.sort_index(ascending=False, inplace=True)

schema_df.head(5)

                                                   QuestionText
Column
YearsCodePro  How many years have you coded professionally (...
YearsCode     Including any education, how many years have y...
WorkWeekHrs    On average, how many hours per week do you work?
WorkRemote                      How often do you work remotely?
WorkPlan                How structured or planned is your work?